<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>859ba504-af8b-4e1a-9bd4-ca196c666b4b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WalletLedger.Application\WalletLedger.Application.csproj" />
    <ProjectReference Include="..\WalletLedger.Infrastructure\WalletLedger.Infrastructure.csproj" />
  </ItemGroup>

</Project>
